[workspace]
members = ["couchbase-lite-core-sys", "couchbase-lite", "chat-demo", "serde-fleece"]

[patch.'crates-io']
couchbase-lite = { path = "couchbase-lite" }
couchbase-lite-core-sys = { path = "couchbase-lite-core-sys" }
